# =============================================================================
# Render Blueprint Specification (Sin Base de Datos interna)
# Este archivo permite desplegar el Web Service en Render vinculándolo a tu
# base de datos externa de Neon.tech.
# =============================================================================

services:
  - type: web
    name: inventario-laboratorio
    env: docker
    dockerfilePath: dockerfile
    plan: free
    numInstances: 1
    envVars:
      - key: PORT
        value: 8080
      - key: RUST_LOG
        value: info
      - key: JWT_SECRET
        generateValue: true # Render generará una clave aleatoria segura de forma automática
      - key: DATABASE_URL
        sync: false # Render te pedirá que pegues tu URL de Neon en la interfaz web al desplegar
